const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number.isFinite(v)?v:a));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const angleDelta=(a,b)=>Math.atan2(Math.sin(b-a),Math.cos(b-a));
const sign=team=>team==='ally'?1:-1;
const other=team=>team==='ally'?'enemy':'ally';
function hash(text){let h=2166136261;for(const ch of String(text||'tank')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function laneFor(tank,time){const h=hash(tank.id),base=((h&255)/255-.5)*420,wave=Math.sin(time*.16+(h>>>8)%17)*95;return base+wave;}
function lineFor(sec,team){const centerX=sec.x+(sec.war?.positionOffset||0),force=sec.war?.[team];return{x:centerX+(team==='ally'?-320:320)+sign(team)*(force?.advance||0),y:sec.y};}
function nearest(list,from){let best=null,bestDistance=Infinity;for(const item of list||[]){if(!item||item.alive===false||item.inactive||item.downed)continue;const d=dist(item,from);if(d<bestDistance){best=item;bestDistance=d;}}return best?{item:best,distance:bestDistance}:null;}
function segmentSmoke(smokes,a,b){const mx=(a.x+b.x)/2,my=(a.y+b.y)/2;return (smokes||[]).some(s=>s.life>0&&Math.hypot(s.x-mx,s.y-my)<Math.max(170,s.r||0));}

export function stepTankTactics(state,dt){if(!state||!Number.isFinite(dt)||dt<=0)return;const time=Number(state.warSimulation?.clock)||Number(state.time)||0;for(const sec of state.sectors||[]){const war=sec.war;if(!war?.vehicles)continue;for(const tank of war.vehicles){if(tank?.type!=='tank'||tank.alive===false)continue;const team=tank.team,foe=other(team),force=war[team],ownLine=lineFor(sec,team),foeLine=lineFor(sec,foe),hpRatio=clamp((Number(tank.hp)||0)/Math.max(1,Number(tank.maxHp)||180),0,1),lane=laneFor(tank,time),base=nearest((war.bases||[]).filter(b=>b.team===team),tank)?.item,enemyTank=nearest((war.vehicles||[]).filter(v=>v.team===foe&&v.alive!==false),tank),enemyUnit=nearest((sec.units||[]).filter(u=>u.team===foe&&!u.inactive&&!u.downed),tank),playerTarget=team==='enemy'&&state.mode==='march'&&state.robot&&dist(tank,state.robot)<6500?state.robot:null;let aim=playerTarget||enemyTank?.item||enemyUnit?.item||foeLine;let tactic='hold';let desired={x:ownLine.x-sign(team)*175,y:sec.y+lane};const damaged=hpRatio<.34,retreat=damaged||['retreat','regroup'].includes(force?.phase);if(retreat&&base){tactic=damaged?'repair-retreat':'fallback';desired={x:base.x-sign(team)*80,y:base.y+lane*.28};}else if(force?.phase==='assault'){tactic='advance';desired={x:ownLine.x-sign(team)*55,y:sec.y+lane*.72};}else if(force?.phase==='suppress'){tactic='fire-support';desired={x:ownLine.x-sign(team)*210,y:sec.y+lane};}else if(force?.phase==='consolidate'){tactic='secure';desired={x:ownLine.x-sign(team)*135,y:sec.y+lane*.55};}if(aim&&segmentSmoke(state.smokes,tank,aim)){tactic='relocate';desired.y+=lane>=0?210:-210;}if(aim&&dist(tank,aim)<760&&!retreat)desired.x-=sign(team)*150;const dx=desired.x-tank.x,dy=desired.y-tank.y,d=Math.hypot(dx,dy),speed=(retreat?20:force?.phase==='assault'?17:12)*(hpRatio<.55?.82:1),step=Math.min(d,speed*dt);if(d>1&&step>0){tank.x+=dx/d*step;tank.y+=dy/d*step;tank.speed=step/Math.max(dt,.001);tank.hullAngle=(Number.isFinite(tank.hullAngle)?tank.hullAngle:Number(tank.angle)||0)+angleDelta(Number.isFinite(tank.hullAngle)?tank.hullAngle:Number(tank.angle)||0,Math.atan2(dy,dx))*(1-Math.exp(-4*dt));}else tank.speed=Math.max(0,(Number(tank.speed)||0)*.82);if(aim){const desiredAim=Math.atan2(aim.y-tank.y,aim.x-tank.x),current=Number.isFinite(tank.turretAngle)?tank.turretAngle:Number(tank.angle)||desiredAim;tank.turretAngle=current+angleDelta(current,desiredAim)*(1-Math.exp(-5.5*dt));if((Number(tank.flash)||0)>.01||d<8)tank.angle=tank.turretAngle;else tank.angle=Number.isFinite(tank.hullAngle)?tank.hullAngle:tank.angle;}tank.tactic=tactic;tank.preferredTarget=aim?.id||null;}}
}
