function addDefCovers(p){if(p.index===0)return;state.covers.push(makeCover(p.x-190,p.y+145,115,22,'sand'),makeCover(p.x+55,p.y+150,125,22,'sand'),makeCover(p.x-65,p.y-175,130,22,'sand'),makeCover(p.x-260,p.y-40,90,24,'wall'))}
function reset(){
 state={time:0,paused:false,mode:'march',armor:100,ammo:{HE:12,SMOKE:6,CLUSTER:5},bearing:90,elevation:45,charge:3,wind:{x:rand(-4,4),y:rand(-2.5,2.5)},robot:{x:420,y:920,r:30,facing:0,turret:0,speed:0},shell:null,smokes:[],tracers:[],effects:[],craters:[],covers:[],units:[],points:[makePoint(680,820,'ALFA',0),makePoint(1420,980,'BRAVO',1),makePoint(2200,760,'CHARLIE',2),makePoint(2860,970,'DELTA',3)],scenery:scenery(),reserveA:70,reserveE:75,spawnA:0,spawnE:0,latestRequest:null,gameOver:false,operation:{phase:'RALLY',timer:18,objective:1,wave:1,plan:'left',phaseStarted:0,shotCommitted:false,assaultStartA:0,assaultCasA:0},counter:{active:false,timer:0,target:null}};
 for(const p of state.points)addDefCovers(p);for(let i=0;i<24;i++){const x=rand(470,2870),y=rand(220,1560);state.covers.push(makeCover(x,y,rand(55,125),rand(18,32),i%4===0?'sand':'wall'))}
 spawnSquad('ally',14,{x:410,y:910},false);spawnSquad('enemy',9,{x:1420,y:980},true);spawnSquad('enemy',7,{x:2200,y:760},true);
 cam={x:900,y:900,zoom:.44,freeUntil:0};moveDir={x:0,y:0};selectedShell='HE';radioLog.innerHTML='';UI.request.classList.add('hidden');UI.end.classList.add('hidden');closeAllModals();setMode('march');
 log('<b>COMANDO:</b> Operação iniciada. A infantaria não vai atacar sem se reunir e reconhecer a posição.','good');log('<b>OBSERVADOR:</b> Quando surgir uma missão de fogo, a força principal espera seu apoio. Você tem tempo para calcular.');updateUI();
}
function spawnSquad(team,n,base,defensive=false){for(let i=0;i<n;i++){const role=i%6===0?'support':i%5===0?'scout':'rifle';const u=makeUnit(team,base.x+rand(-90,90),base.y+rand(-130,130),role,i%3);u.state=defensive?'defend':'rally';state.units.push(u);if(team==='ally')state.reserveA=Math.max(0,state.reserveA-1);else state.reserveE=Math.max(0,state.reserveE-1)}}
