function updateHelp(){if(!state.latestRequest){UI.helpEx.innerHTML='Sem missão de fogo ativa.';return}const r=state.robot,q=state.latestRequest,dx=q.x-r.x,dy=q.y-r.y,d=Math.hypot(dx,dy);UI.helpEx.innerHTML=`Alvo <b>X${fmt(q.x)} Y${fmt(q.y)}</b><br>Mamute <b>X${fmt(r.x)} Y${fmt(r.y)}</b><br>ΔX ${Math.round(dx)} • ΔY ${Math.round(dy)} • distância ≈ <b>${Math.round(d)}m</b>.`}
function stepControl(kind,delta){if(kind==='bearing')state.bearing=(state.bearing+delta+360)%360;if(kind==='elevation')state.elevation=clamp(state.elevation+delta,20,75);if(kind==='charge')state.charge=clamp(state.charge+delta,1,5);updateUI()}
function holdStep(el){const [kind,ds]=el.dataset.step.split(':'),delta=+ds;const run=()=>stepControl(kind,delta);run();clearTimeout(repeatTimer);clearInterval(repeatLoop);repeatTimer=setTimeout(()=>repeatLoop=setInterval(run,95),340)}
function clearRepeat(){clearTimeout(repeatTimer);clearInterval(repeatLoop)}
function closeAllModals(){$('menuModal').classList.add('hidden');$('helpModal').classList.add('hidden');$('installModal').classList.add('hidden')}
function openMenu(){state.paused=true;$('menuStatus').textContent='Batalha pausada • '+(PHASES[state.operation.phase]||'');$('menuModal').classList.remove('hidden')}
function resume(){closeAllModals();state.paused=false}
function setup(){
 $('deployBtn').addEventListener('click',()=>setMode('artillery'));$('undeployBtn').addEventListener('click',()=>setMode('march'));$('fireBtn').addEventListener('click',fireShell);$('centerBtn').addEventListener('click',()=>{cam.x=state.robot.x;cam.y=state.robot.y;cam.zoom=.46});$('radioBtn').addEventListener('click',()=>$('radioDrawer').classList.toggle('hidden'));$('closeRadio').addEventListener('click',()=>$('radioDrawer').classList.add('hidden'));$('menuBtn').addEventListener('click',openMenu);$('resumeBtn').addEventListener('click',resume);$('restartBtn').addEventListener('click',reset);$('endRestart').addEventListener('click',reset);$('helpBtn').addEventListener('click',()=>{$('menuModal').classList.add('hidden');updateHelp();$('helpModal').classList.remove('hidden')});$('closeHelp').addEventListener('click',resume);$('resumeHelp').addEventListener('click',resume);$('cleanBtn').addEventListener('click',async()=>{try{if(document.documentElement.requestFullscreen){await document.documentElement.requestFullscreen();resume();return}}catch(e){}$('menuModal').classList.add('hidden');$('installModal').classList.remove('hidden')});$('closeInstall').addEventListener('click',resume);
 UI.request.addEventListener('click',()=>{if(!state.latestRequest)return;cam.x=state.latestRequest.x;cam.y=state.latestRequest.y;cam.zoom=.62;cam.freeUntil=state.time+8});
 document.querySelectorAll('[data-shell]').forEach(b=>b.addEventListener('click',()=>{selectedShell=b.dataset.shell;document.querySelectorAll('[data-shell]').forEach(x=>x.classList.toggle('active',x===b))}));
 document.querySelectorAll('[data-step]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);holdStep(b)});b.addEventListener('pointerup',clearRepeat);b.addEventListener('pointercancel',clearRepeat);b.addEventListener('pointerleave',clearRepeat)});
 const joy=$('joystick'),knob=$('joyKnob');function setJoy(e){const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.34,d=Math.hypot(dx,dy)||1,k=Math.min(1,max/d);dx*=k;dy*=k;knob.style.transform=`translate(${dx}px,${dy}px)`;moveDir={x:dx/max,y:dy/max}}
 joy.addEventListener('pointerdown',e=>{e.preventDefault();joyPointer=e.pointerId;joy.setPointerCapture(e.pointerId);setJoy(e)});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyPointer)setJoy(e)});const endJoy=e=>{if(e.pointerId!==joyPointer)return;joyPointer=null;moveDir={x:0,y:0};knob.style.transform='translate(0,0)'};joy.addEventListener('pointerup',endJoy);joy.addEventListener('pointercancel',endJoy);
 canvas.addEventListener('pointerdown',e=>{if(state.shell)return;const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;canvas.setPointerCapture(e.pointerId);if(mapDrag&&mapDrag.id!==e.pointerId){pinch={id1:mapDrag.id,id2:e.pointerId,startDist:Math.hypot(x-mapDrag.x,y-mapDrag.y),startZoom:cam.zoom};return}mapDrag={id:e.pointerId,x,y,cx:cam.x,cy:cam.y}});
 canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(pinch&&e.pointerId===pinch.id2&&mapDrag){const d=Math.hypot(x-mapDrag.x,y-mapDrag.y);cam.zoom=clamp(pinch.startZoom*(d/pinch.startDist),.32,.95);return}if(mapDrag&&e.pointerId===mapDrag.id&&!pinch){cam.x=clamp(mapDrag.cx-(x-mapDrag.x)/cam.zoom,0,WORLD.w);cam.y=clamp(mapDrag.cy-(y-mapDrag.y)/cam.zoom,0,WORLD.h)}});
 const endMap=e=>{if(mapDrag&&e.pointerId===mapDrag.id)mapDrag=null;pinch=null};canvas.addEventListener('pointerup',endMap);canvas.addEventListener('pointercancel',endMap)
}
