function drawGrid(){ctx.save();ctx.strokeStyle='rgba(255,255,255,.055)';ctx.lineWidth=1;ctx.fillStyle='rgba(255,255,255,.22)';ctx.font='10px system-ui';for(let x=0;x<=WORLD.w;x+=100){const a=worldToScreen(x,0),b=worldToScreen(x,WORLD.h);if(a.x<-30||a.x>canvas.width+30)continue;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();const t=worldToScreen(x,cam.y);ctx.fillText(String(x),t.x+3,14)}for(let y=0;y<=WORLD.h;y+=100){const a=worldToScreen(0,y),b=worldToScreen(WORLD.w,y);if(a.y<-30||a.y>canvas.height+30)continue;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.fillText(String(y),4,a.y-3)}ctx.restore()}
function drawWorld(){
 ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#1b252b';ctx.fillRect(0,0,canvas.width,canvas.height);
 ctx.save();ctx.strokeStyle=colors.road;ctx.lineWidth=28*cam.zoom;ctx.lineCap='round';ctx.beginPath();let s=worldToScreen(0,600);ctx.moveTo(s.x,s.y);for(let x=200;x<=2200;x+=300){let p=worldToScreen(x,600+Math.sin(x*.006)*110);ctx.lineTo(p.x,p.y)}ctx.stroke();ctx.restore();
 drawGrid();
 for(const c of state.covers){const p=worldToScreen(c.x,c.y);ctx.fillStyle='#4d595f';ctx.fillRect(p.x,p.y,c.w*cam.zoom,c.h*cam.zoom);ctx.fillStyle='rgba(0,0,0,.18)';ctx.fillRect(p.x+5,p.y+5,c.w*cam.zoom,c.h*cam.zoom)}
 for(const p of state.points){const q=worldToScreen(p.x,p.y),owner=p.owner==='ally'?colors.ally:p.owner==='enemy'?colors.enemy:colors.neutral;ctx.strokeStyle=owner;ctx.lineWidth=3;ctx.beginPath();ctx.arc(q.x,q.y,p.r*cam.zoom,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(0,0,0,.35)';ctx.fillRect(q.x-32,q.y-40,64,17);ctx.fillStyle=owner;ctx.font='700 11px system-ui';ctx.textAlign='center';ctx.fillText(p.name,q.x,q.y-28);ctx.fillStyle='#10161b';ctx.fillRect(q.x-30,q.y+28,60,6);ctx.fillStyle=owner;const val=(p.progress+100)/200;ctx.fillRect(q.x-30,q.y+28,60*val,6);if(p.fort>0){ctx.fillStyle='#8c8f85';ctx.fillRect(q.x-20,q.y-8,40,16);ctx.fillStyle='#c0bda8';ctx.fillText('DEF',q.x,q.y+4)}ctx.textAlign='start'}
 for(const s of state.smokes){const q=worldToScreen(s.x,s.y);const alpha=Math.min(.35,s.life/12*.35);ctx.fillStyle=`rgba(190,199,204,${alpha})`;ctx.beginPath();ctx.arc(q.x,q.y,s.r*cam.zoom,0,Math.PI*2);ctx.fill()}
 for(const u of state.units){const q=worldToScreen(u.x,u.y);if(q.x<-20||q.x>canvas.width+20||q.y<-20||q.y>canvas.height+20)continue;ctx.fillStyle=u.team==='ally'?colors.ally:colors.enemy;ctx.beginPath();ctx.arc(q.x,q.y,(u.role==='heavy'?6:4.5)*Math.max(.8,cam.zoom),0,Math.PI*2);ctx.fill();if(u.supp>.55){ctx.strokeStyle='#f1d781';ctx.beginPath();ctx.arc(q.x,q.y,9,0,Math.PI*2);ctx.stroke()}}
 const r=worldToScreen(state.robot.x,state.robot.y);ctx.save();ctx.translate(r.x,r.y);ctx.fillStyle='#d7b464';ctx.fillRect(-18,-13,36,26);ctx.fillStyle='#74613e';ctx.fillRect(-24,-16,8,32);ctx.fillRect(16,-16,8,32);ctx.strokeStyle='#f0d89e';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,-4);ctx.lineTo(28,-4);ctx.stroke();ctx.fillStyle='#fff';ctx.font='700 10px system-ui';ctx.fillText('M-47',-15,-20);ctx.restore();
 if(state.shell){const s=state.shell,q=worldToScreen(s.x,s.y);ctx.fillStyle='#ffd976';ctx.beginPath();ctx.arc(q.x,q.y,5+Math.min(5,s.z*.03),0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(255,217,118,.18)';ctx.beginPath();ctx.arc(q.x,q.y,14,0,Math.PI*2);ctx.fill();ctx.font='11px system-ui';ctx.fillStyle='#fff';ctx.fillText(`ALT ${Math.max(0,Math.round(s.z))}m`,q.x+10,q.y-10)}
 for(const e of state.explosions){if(e.type==='tracer'){const a=worldToScreen(e.x,e.y),b=worldToScreen(e.x2,e.y2);ctx.strokeStyle=e.life>.06?'rgba(255,230,150,.8)':'rgba(255,230,150,.25)';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}else{const q=worldToScreen(e.x,e.y),rr=(e.max*(1-e.life/.8))*cam.zoom;ctx.fillStyle=`rgba(255,165,72,${Math.max(0,e.life/.8)*.5})`;ctx.beginPath();ctx.arc(q.x,q.y,rr,0,Math.PI*2);ctx.fill()}}
 if(state.gameOver){ctx.fillStyle='rgba(0,0,0,.45)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='700 28px system-ui';ctx.fillText('BATALHA ENCERRADA',canvas.width/2,canvas.height/2);ctx.font='14px system-ui';ctx.fillText('Use “Nova Batalha” para reiniciar',canvas.width/2,canvas.height/2+28);ctx.textAlign='start'}
}
function updateUI(){
 const nearest=[...state.points].sort((a,b)=>Math.hypot(a.x-state.robot.x,a.y-state.robot.y)-Math.hypot(b.x-state.robot.x,b.y-state.robot.y))[0];UI.sector.textContent='Setor: '+nearest.name;UI.mode.textContent=state.mode==='march'?'MODO MARCHA':'ARTILHARIA TRAVADA';UI.score.textContent=`Impacto: ${state.impactScore}`;UI.robotCoord.textContent=`X ${fmt(state.robot.x)} • Y ${fmt(state.robot.y)}`;UI.armor.textContent=Math.max(0,Math.round(state.armor))+'%';UI.he.textContent=state.ammo.HE;UI.smoke.textContent=state.ammo.SMOKE;UI.frag.textContent=state.ammo.CLUSTER;UI.coord.textContent=`CÂMERA X${fmt(cam.x)} Y${fmt(cam.y)}`;UI.wind.textContent=`VENTO ${state.wind.x>=0?'L':'O'} ${Math.abs(state.wind.x).toFixed(1)} / ${state.wind.y>=0?'S':'N'} ${Math.abs(state.wind.y).toFixed(1)}`;const allyPts=state.points.filter(p=>p.owner==='ally').length;UI.front.textContent=`FRONT ${allyPts}/${state.points.length} PONTOS • A:${state.units.filter(u=>u.team==='ally').length} E:${state.units.filter(u=>u.team==='enemy').length}`;
}
function applyMode(m){state.mode=m;document.getElementById('moveWrap').classList.toggle('hide',m==='artillery');document.getElementById('aimPanel').classList.toggle('show',m==='artillery');document.getElementById('marchBtn').classList.toggle('active',m==='march');document.getElementById('deployBtn').classList.toggle('active',m==='artillery');moveDir={x:0,y:0};updateUI();}
function setupControls(){
 document.getElementById('marchBtn').addEventListener('click',()=>applyMode('march'));document.getElementById('deployBtn').addEventListener('click',()=>applyMode('artillery'));document.getElementById('undeployBtn').addEventListener('click',()=>applyMode('march'));document.getElementById('fireBtn').addEventListener('click',fireShell);document.getElementById('newBattle').addEventListener('click',reset);
 document.querySelectorAll('[data-shell]').forEach(b=>b.addEventListener('click',()=>{selectedShell=b.dataset.shell;document.querySelectorAll('[data-shell]').forEach(x=>x.classList.toggle('active',x===b));}));
 const bearing=document.getElementById('bearing'),elev=document.getElementById('elevation'),charge=document.getElementById('charge');const outs=[['bearingOut',bearing,v=>String(v).padStart(3,'0')+'°'],['elevationOut',elev,v=>v+'°'],['chargeOut',charge,v=>v]];outs.forEach(([id,el,f])=>el.addEventListener('input',()=>document.getElementById(id).textContent=f(el.value)));
 document.querySelectorAll('[data-move]').forEach(b=>{const set=()=>{if(state.mode!=='march')return;const d=b.dataset.move;if(d==='up')moveDir={x:0,y:-1};if(d==='down')moveDir={x:0,y:1};if(d==='left')moveDir={x:-1,y:0};if(d==='right')moveDir={x:1,y:0};if(d==='stop')moveDir={x:0,y:0};};b.addEventListener('pointerdown',e=>{e.preventDefault();set()});b.addEventListener('pointerup',()=>{if(b.dataset.move!=='stop')moveDir={x:0,y:0}});b.addEventListener('pointercancel',()=>moveDir={x:0,y:0});});
 document.getElementById('centerRobot').addEventListener('click',()=>{cam.x=state.robot.x;cam.y=state.robot.y});document.getElementById('zoomIn').addEventListener('click',()=>cam.zoom=clamp(cam.zoom+.12,.48,1.25));document.getElementById('zoomOut').addEventListener('click',()=>cam.zoom=clamp(cam.zoom-.12,.48,1.25));
 canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),sx=(e.clientX-r.left)*canvas.width/r.width,sy=(e.clientY-r.top)*canvas.height/r.height;drag={sx,sy,cx:cam.x,cy:cam.y};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;const r=canvas.getBoundingClientRect(),sx=(e.clientX-r.left)*canvas.width/r.width,sy=(e.clientY-r.top)*canvas.height/r.height;cam.x=clamp(drag.cx-(sx-drag.sx)/cam.zoom,0,WORLD.w);cam.y=clamp(drag.cy-(sy-drag.sy)/cam.zoom,0,WORLD.h)});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);
}
function loop(t){const dt=Math.min(.035,(t-last)/1000||0);last=t;update(dt);drawWorld();requestAnimationFrame(loop)}
setupControls();reset();requestAnimationFrame(loop);
