function setRequestForDefense(p){const defs=activeDefs(p);if(!defs.length)return;const d=defs.sort((a,b)=>a.type==='MORTAR'?-1:1)[0];const caller=alive('ally').find(u=>u.role==='scout')||alive('ally')[0];state.latestRequest={x:d.x,y:d.y,type:d.type,defense:d,unit:caller?.callsign||'OBS',time:state.time};UI.reqTitle.textContent=d.type+' BLOQUEANDO';UI.reqText.textContent=`X${fmt(d.x)} Y${fmt(d.y)}`;UI.reqHint.textContent='Força principal aguardando seu fogo';UI.request.classList.remove('hidden');log(`<b>📡 ${state.latestRequest.unit}:</b> ${d.type} identificado em X${fmt(d.x)} Y${fmt(d.y)}. Força de assalto aguardando fogo.`,'request');updateHelp()}
function changePhase(name,timer){state.operation.phase=name;state.operation.timer=timer;state.operation.phaseStarted=state.time;if(name==='PREP')state.operation.shotCommitted=false;log(`<b>COMANDO:</b> ${PHASES[name]}.`,'good')}
function beginAssault(){const a=alive('ally').length;state.operation.assaultStartA=a;state.operation.assaultCasA=0;UI.request.classList.add('hidden');changePhase('ASSAULT',34);log(`<b>COMANDO:</b> Assalto iniciado pelos flancos. ${activeDefs(objective()).length} arma(s) ainda ativa(s).`,'good')}
function updateOperation(dt){const op=state.operation,p=objective();if(!p){finish(true);return}op.timer-=dt;const a=alive('ally').length;
 if(a===0&&state.reserveA>0){op.timer=Math.max(op.timer,7);if(state.time-op.phaseStarted>7){spawnSquad('ally',Math.min(8,state.reserveA),{x:state.points[Math.max(0,p.index-1)].x+80,y:state.points[Math.max(0,p.index-1)].y},false);changePhase('RALLY',20)}}
 if(op.phase==='RALLY'){if(op.timer<=0){if(a<9&&state.reserveA>0){spawnSquad('ally',Math.min(6,state.reserveA),{x:state.points[Math.max(0,p.index-1)].x+90,y:state.points[Math.max(0,p.index-1)].y},false);op.timer=10;log('<b>COMANDO:</b> aguardando reforços antes de reconhecer a posição.')}else changePhase('RECON',14)}}
 else if(op.phase==='RECON'&&op.timer<=0){if(activeDefs(p).length){changePhase('PREP',9999);setRequestForDefense(p)}else beginAssault()}
 else if(op.phase==='PREP'){if(!activeDefs(p).length)beginAssault();else if(state.operation.shotCommitted&&state.time-state.operation.shotCommitted>5)beginAssault()}
 else if(op.phase==='ASSAULT'){
   const nearA=alive('ally').filter(u=>dist(u,p)<p.r+30).length,nearE=alive('enemy').filter(u=>dist(u,p)<p.r+70).length;if(nearA>nearE&&nearA>=3)p.progress=clamp(p.progress+dt*(nearA-nearE)*3.2,-100,100);else if(nearE>nearA)p.progress=clamp(p.progress-dt*(nearE-nearA)*1.3,-100,100);
   if(p.progress>=100){p.owner='ally';changePhase('CONSOLIDATE',18);log(`<b>COMANDO:</b> ${p.name} capturado. Consolidando e trazendo munição.`,'good');state.latestRequest=null;UI.request.classList.add('hidden');if(state.reserveA>0)spawnSquad('ally',Math.min(4,state.reserveA),{x:p.x-160,y:p.y},false);launchCounter(p)}
   else if(op.timer<=0||a<Math.max(4,op.assaultStartA*.52)){changePhase('RETREAT',13);log('<b>COMANDO:</b> investida falhou. Unidades recuando para recompor, não insistir até a morte.','bad')}
 }
 else if(op.phase==='RETREAT'&&op.timer<=0){changePhase('RALLY',18);if(state.reserveA>0)spawnSquad('ally',Math.min(5,state.reserveA),{x:state.points[Math.max(0,p.index-1)].x+80,y:state.points[Math.max(0,p.index-1)].y},false)}
 else if(op.phase==='CONSOLIDATE'&&op.timer<=0){op.objective++;op.wave++;if(op.objective>=state.points.length){finish(true)}else{changePhase('RALLY',21);if(state.reserveE>0)spawnSquad('enemy',Math.min(5,state.reserveE),{x:state.points[op.objective].x+170,y:state.points[op.objective].y},true)}}
}
