import { smokeBlocksLine } from '../modules/war-simulation-core.js';

export const SERVER_RECON_LIMITS = Object.freeze({ radioSight: 1200, radioCooldown: 8, lifetime: 45, reports: 80, contacts: 24 });
const teams = ['ally', 'enemy'];
const opponent = team => team === 'ally' ? 'enemy' : 'ally';
const point = value => Number.isFinite(value?.x) && Number.isFinite(value?.y);
const distance = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
const live = value => value && value.alive !== false && !value.inactive && !value.downed && (value.hp === undefined || value.hp > 0) && point(value);
const mamuteTeam = m => m.faction === 'axis' ? 'enemy' : m.faction === 'allies' ? 'ally' : null;

/** Last-known observations generated by actual server entities, never map zoom. */
export function createServerRecon({ state, theatre, airWar } = {}) {
  state.recon ||= { version: 1, clock: Number(state.time) || 0, serial: 0, nextScanAt: 0, nextRadioAt: {}, seenAir: {}, reports: [] };
  if (state.recon.version !== 1) throw new Error('Unsupported reconnaissance checkpoint');
  const recon = state.recon;
  const battlefield = state.battlefield;
  function saveReport(report) {
    if (!report.contacts.length) return;
    recon.reports = recon.reports.filter(old => old.sourceId !== report.sourceId || old.team !== report.team || old.source !== report.source);
    recon.reports.push(report);
    recon.reports = recon.reports.slice(-SERVER_RECON_LIMITS.reports);
  }
  function groundContacts() {
    const contacts = [];
    for (const sector of battlefield.sectors || []) {
      for (const unit of sector.units || []) if (live(unit) && teams.includes(unit.team)) contacts.push({
        id: unit.id || `${sector.id}-${unit.team}-soldier-${unit.slot}`, type: 'infantry', team: unit.team, x: unit.x, y: unit.y, count: 1,
      });
      for (const asset of [...(sector.assets || []), ...(sector.war?.vehicles || []), ...(sector.war?.mortars || []), ...(sector.war?.bases || [])]) {
        if (live(asset) && teams.includes(asset.team)) contacts.push({ id: asset.id, type: asset.type || 'structure', team: asset.team, x: asset.x, y: asset.y });
      }
    }
    for (const m of Object.values(state.mamutes || {})) if (!m.destroyed && m.robot?.armor > 0 && point(m.robot) && mamuteTeam(m)) {
      contacts.push({ id: m.id, type: 'mamute', name: m.name, team: mamuteTeam(m), x: m.robot.x, y: m.robot.y });
    }
    for (const [id, node] of theatre.territory || []) {
      const endpoint = theatre.logistics.getNode(id), sector = theatre.records.get(id)?.sector;
      if (!teams.includes(node.owner) || node.contested || !node.structures?.length || !endpoint?.alive || endpoint.team !== node.owner || !point(sector)) continue;
      contacts.push({ id, type: 'base', team: node.owner, x: sector.x, y: sector.y, structures: [...node.structures] });
    }
    for (const convoy of theatre.logistics.snapshot?.().convoys || []) {
      if (!['moving', 'blocked'].includes(convoy.status) || convoy.hp <= 0 || !point(convoy.position) || !teams.includes(convoy.team)) continue;
      contacts.push({ id: convoy.id, type: 'convoy', team: convoy.team, x: convoy.position.x, y: convoy.position.y, count: 1 });
    }
    return contacts;
  }
  function radio() {
    let contacts = null;
    for (const sector of battlefield.sectors || []) for (const unit of sector.units || []) {
      if (!live(unit) || !teams.includes(unit.team)) continue;
      // The same equipment slot survives LOD materialization. A killed operator
      // does not hand a magical radio to the next arbitrary living soldier.
      const equipped = unit.radio === true || unit.role === 'radio' || (unit.radio !== false && Number.isInteger(unit.slot) && unit.slot % 8 === 0);
      if (!equipped) continue;
      unit.radio = true;
      const sourceId = `radio:${sector.id}:${unit.team}:${unit.slot ?? unit.id}`;
      if ((recon.nextRadioAt[sourceId] || 0) > recon.clock) continue;
      recon.nextRadioAt[sourceId] = recon.clock + SERVER_RECON_LIMITS.radioCooldown;
      contacts ||= groundContacts();
      const seen = new Set();
      const observed = contacts.filter(contact => contact.team === opponent(unit.team) && contact.id &&
        distance(unit, contact) <= SERVER_RECON_LIMITS.radioSight && !smokeBlocksLine(battlefield.smokes || [], unit, contact))
        .sort((a, b) => distance(unit, a) - distance(unit, b))
        .filter(contact => { if (seen.has(contact.id)) return false; seen.add(contact.id); return true; })
        .slice(0, SERVER_RECON_LIMITS.contacts).map(({ team: _team, ...contact }) => structuredClone(contact));
      saveReport({ id: `radio-report-${++recon.serial}`, sourceId, source: 'radio', team: unit.team,
        sectorId: sector.strategicSectorId || sector.strategicId || sector.id,
        x: unit.x, y: unit.y, observedAt: recon.clock, expires: recon.clock + SERVER_RECON_LIMITS.lifetime, contacts: observed });
    }
  }
  function planes() {
    if (!airWar?.snapshot) return;
    const airClock = Number.isFinite(battlefield.airWar?.clock) ? battlefield.airWar.clock : recon.clock;
    for (const team of teams) {
      const air = airWar.snapshot({ team });
      const sources = new Set((air.aircraft || []).filter(plane => live(plane) && plane.team === team && plane.type === 'recon' && plane.life > 0).map(plane => plane.id));
      for (const report of air.reports || []) {
        if (report.type !== 'recon-contact' || report.team !== team || !sources.has(report.sourceId) || !report.id || recon.seenAir[report.id] || !point(report)) continue;
        const age = Math.max(0, airClock - (Number(report.time) || 0));
        const observedAt = recon.clock - age, expires = observedAt + SERVER_RECON_LIMITS.lifetime;
        recon.seenAir[report.id] = recon.clock + 100;
        if (expires <= recon.clock) continue;
        const contacts = (report.observations || []).filter(contact => point(contact) && distance(report, contact) <= 1800)
          .slice(0, SERVER_RECON_LIMITS.contacts).map((contact, index) => ({
            id: contact.targetId || contact.sectorId || `${report.id}-contact-${index}`, type: contact.kind || 'contact', x: contact.x, y: contact.y,
            ...(Number.isFinite(contact.enemyStrength) ? { count: Math.max(0, Math.round(contact.enemyStrength)) } : {}),
          }));
        saveReport({ id: `plane-${report.id}`, sourceId: report.sourceId, source: 'plane', team,
          x: report.x, y: report.y, observedAt, expires, contacts });
      }
    }
  }
  function prune() {
    recon.reports = recon.reports.filter(report => report.expires > recon.clock).slice(-SERVER_RECON_LIMITS.reports);
    for (const [id, until] of Object.entries(recon.nextRadioAt)) if (until < recon.clock - 45) delete recon.nextRadioAt[id];
    for (const [id, until] of Object.entries(recon.seenAir)) if (until < recon.clock) delete recon.seenAir[id];
  }
  function step(dt) {
    if (!Number.isFinite(dt) || dt <= 0) return;
    recon.clock = Math.max(Number(state.time) || 0, recon.clock + dt);
    prune();
    if (recon.nextScanAt > recon.clock) return;
    recon.nextScanAt = recon.clock + .5;
    radio();
    planes();
  }
  function snapshot(team) {
    if (!teams.includes(team)) return { reports: [] };
    return structuredClone({ reports: recon.reports.filter(report => report.team === team && report.expires > recon.clock) });
  }
  return { step, snapshot };
}
